const randoomBeersTypes = {

    LOADD_RANDOOM_LT_ABV:"LOADD_RANDOOM_LT_ABV",
    LOADD_RANDOOM_GT_ABV:"LOADD_RANDOOM_GT_ABV",
    LOADD_RANDOOM_ERROR:"LOADD_RANDOOM_ERROR"
}

export default randoomBeersTypes;